language: node_js

node_js:
  - "0.10"

script: 'make test-cov'
after_success: 'make coveralls'
 
notifications:
  email:
    - 'updates@joo.la'
  irc:
    channels:
      - 'chat.freenode.net#joola.io'
    skip_join: true